apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-config
data:
  apploglevel: info
  appdatadir: /var/data
  prometheus.yml: |
    global:
      scrape_interval: 15s
      scrape_timeout: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']