apiVersion: v1
kind: Pod
metadata:
  name: prob-pod
spec:
  containers:
    - name: prob-pod
      image: registry.cn-beijing.aliyuncs.com/lml_test/kubernetes-test:1.0.0-SNAPSHOT
      ports:
        - containerPort: 9090
      startupProbe:
        failureThreshold: 12
        periodSeconds: 10
        httpGet:
          port: 9090
          path: /index
      livenessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 1
        failureThreshold: 2
        httpGet:
          #host: 默认为podIP
          #scheme: 默认为http
          port: 9090
          path: /index
      readinessProbe:
        initialDelaySeconds: 30
        periodSeconds: 30
        timeoutSeconds: 5
        successThreshold: 2
        failureThreshold: 1
        httpGet:
          port: 9090
          path: /index
