apiVersion: v1
kind: Pod
metadata:
  name: volume-pod
spec:
  containers:
    - name: volume-pod
      image: registry.cn-beijing.aliyuncs.com/lml_test/kubernetes-test:1.0.0-SNAPSHOT
      ports:
        - containerPort: 9090
      volumeMounts:
        - mountPath: /usr/local
          name: tomcat-volume
  volumes:
    - name: tomcat-volume
      emptyDir: {}