apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    protocol: TCP
    targetPort: web
  selector:
    prometheus: prometheus
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  namespace: monitoring
spec:
  externalUrl: http://monitoring-lml.izaodao.com/prometheus
  serviceAccountName: prometheus
  alerting:
    alertmanagers:
    - namespace: monitoring
      name: alertmanager
      port: web
  serviceMonitorSelector:
    matchLabels:
      team: frontend
  ruleSelector:
    matchLabels:
      role: alert-rules
      prometheus: prometheus
  resources:
    requests:
      memory: 400Mi
  enableAdminAPI: false