apiVersion: v1
kind: Pod
metadata:
  name: subpath-pod
spec:
  containers:
    - name: nginx-1
      image: nginx
      volumeMounts:
        - mountPath: /usr/loca
          name: nginx-volume
          subPath: nginx-1
  volumes:
    - name: nginx-volume
      configMap:
        name: subpath-configmap

---

apiVersion: v1
kind: Pod
metadata:
  name: subpath-pod2
spec:
  containers:
    - name: nginx-2
      image: nginx
      volumeMounts:
        - mountPath: /usr/loca
          name: nginx-volume
  volumes:
    - name: nginx-volume
      configMap:
        name: subpath-configmap2

