apiVersion: v1
kind: Pod
metadata:
  name: configmap-demo-pod
spec:
  containers:
    - name: demo
      image: alpine
      command: ["sleep", "3600"]
      env:
        - name: PLAYER_INITIAL_LIVES
          valueFrom:
            configMapKeyRef:
              key: player_initial_lives
              name: demo-configmap
        - name: UI_PROPERTIES_FILE_NAME
          valueFrom:
            configMapKeyRef:
              name: demo-configmap
              key: ui_properties_file_name
      volumeMounts:
        - mountPath: /config
          name: config
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: demo-configmap
        items:
          - key: "game.properties"
            path: "g.properties"
          - key: "user-interface.properties"
            path: "u.properties"

