apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-configmap
data:
  # 类属性
  player_initial_lives: "3"
  ui_properties_file_name: "user-interface.properties"
  # 类文件
  game.properties: |
    enemy.types=aliens,monsters
    player.maximum-lives=5
  user-interface.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true