apiVersion: v1
kind: Secret
metadata:
  name: thanos-objstore-config
  namespace: monitoring
type: Opaque
stringData:
  thanos.yaml: |
    type: ALIYUNOSS
    config:
      endpoint: "oss-cn-hangzhou.aliyuncs.com"
      bucket: "zaodao-thanos-test"
      access_key_id: "****"
      access_key_secret: "****"