global:
  resolve_timeout: 5m
  smtp_smarthost: 'smtp.qq.com:465'
  smtp_from: '823202049@qq.com'
  smtp_auth_username: '823202049@qq.com'
  smtp_auth_password: '*****'
  smtp_require_tls: false
route:
  group_by: ['instance']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'default'
receivers:
  - name: 'default'
    email_configs:
    - to: 'limingliang@izaodao.com'
