global:
  scrape_interval: 15s #默认15s
  evaluation_interval: 10s
  external_labels:
    monitor: 'codelab-monitor'
alerting:
  alertmanagers:
  - static_configs:
      - targets: [ 'localhost:9093' ]
rule_files:
  - 'rule.yml'
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node'
    scrape_interval: 5s
    static_configs:
      - targets: [ '172.17.156.228:8080' ]
        labels:
          group: 'prod'