apiVersion: v1
kind: Secret
metadata:
  name: alertmanager-config
  namespace: cattle-monitoring-system
type: Opaque
stringData:
  alertmanager.yaml: |
    global:
      resolve_timeout: 5m
      wechat_api_url: 'https://qyapi.weixin.qq.com/cgi-bin/'
      wechat_api_secret: '***'
      wechat_api_corp_id: '***'
    route:
      receiver: default
      group_by:
        - alertname
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
      routes:
        - match:
            alertname: Watchdog
          receiver: 'null'
        - match:
            namespace: ingress-nginx
          receiver: 'java'
    receivers:
      - name: 'null'
      - name: 'default'
        wechat_configs:
        - send_resolved: true
          agent_id: '***'
          to_party: '***'
          to_user: '***|***'
          message: '{{ template "wechat.tmpl" . }}'
      - name: 'java'
        wechat_configs:
        - send_resolved: true
          agent_id: '***'
          to_party: '***'
          message: '{{ template "wechat.tmpl" . }}'
    inhibit_rules:
      - equal:
        - namespace
        - alertname
        source_match:
          severity: critical
        target_match_re:
          severity: warning|info
      - equal:
        - namespace
        - alertname
        source_match:
          severity: warning
        target_match_re:
          severity: info
    templates:
      - /etc/alertmanager/config/*.tmpl

  wechat_template.tmpl: |
    {{ define "__alert_list" }}{{ range . }}
    告警名称: {{ .Labels.alertname }}
    告警信息: {{ .Annotations.summary }}
    告警级别: {{ .Labels.severity }}
    告警主机: {{ .Labels.instance }}
    告警详情: {{ .Annotations.description }}{{ .Annotations.message }}
    告警时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    ------------------------------
    {{ end }}{{ end }}

    {{ define "__resolved_list" }}{{ range . }}
    告警名称: {{ .Labels.alertname }}
    告警信息: {{ .Annotations.summary }}
    告警级别: {{ .Labels.severity }}
    告警主机: {{ .Labels.instance }}
    告警详情: {{ .Annotations.description }}{{ .Annotations.message }}
    告警时间: {{ (.StartsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    恢复时间: {{ (.EndsAt.Add 28800e9).Format "2006-01-02 15:04:05" }}
    ------------------------------
    {{ end -}}{{ end }}

    {{ define "wechat.tmpl" }}
    {{ if gt (len .Alerts.Firing) 0 }}
    ====侦测到{{ .Alerts.Firing | len  }}个故障====
    {{ template "__alert_list" .Alerts.Firing }}
    {{ end }}
    {{ if gt (len .Alerts.Resolved) 0 }}
    ====恢复{{ .Alerts.Resolved | len  }}个故障====
    {{ template "__resolved_list" .Alerts.Resolved }}
    {{ end }}
    {{ end }}