apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-rules
  namespace: monitoring
data:
  node-up.yaml: |
    groups:
    - name: server_rules
      rules:
      - alert: 机器宕机
        expr: up{job="node-exporter"} != 1
        for: 1m
        labels:
          instance: "{{$labels.instance}}"
        annotations:
          summary: "机器{{$labels.instance}}处于down的状态"
          description: "{{$labels.instance}} of job {{$labels.job}} 已经处于down状态超过1分钟，请及时处理"

  cpu-usage.yaml: |
    groups:
    - name: cpu_rules
      rules:
      - alert: cpu剩余量过低
        expr: (1-(sum(increase(node_cpu_seconds_total{mode="idle"}[2m]))by(instance))/(sum(increase(node_cpu_seconds_total[2m]))by(instance)))*100
        for: 1m
        labels:
          instance: "{{$labels.instance}}"
        annotations:
          summary: "机器 {{$labels.instance}} cpu 已用超过设定值"
          description: "{{$labels.instance}} CPU 用量已超过 85% (current value is: {{$value}})，请及时处理。"