apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gold
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true" #是否为默认storageclass
provisioner: kuberntes.io/gec-pd
parameters:
  type: pd-ssd