apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: slow
#  selector:
#    matchLabels:
#    matchExpressions:
#      - key:
#        operator: