apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app.kubernetes.io/name: calico-felix
    app.kubernetes.io/part-of: calico
    app.kubernetes.io/version: 3.18.4
  name: calico-felix
  namespace: monitoring
spec:
  endpoints:
    - interval: 30s
      port: metrics-port
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: calico-node