apiVersion: v1
kind: Service
metadata:
  name: kube-controllers-metrics-svc
  namespace: kube-system
  labels:
    k8s-app: calico-kube-controllers
spec:
  selector:
    k8s-app: calico-kube-controllers
  ports:
    - port: 9094
      name: metrics-port
      targetPort: 9094